# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install PyQtWebEngine
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Build
      run: |
        pyinstaller main.py settings.py windows/download.py windows/main_window.py windows/progress.py windows/settings.py windows/view.py --noconsole --clean --onefile
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: main
        path: dist/
  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install PyQtWebEngine
        pip install -r requirements.txt
    - name: Build
      run: |
        pyinstaller main.py settings.py windows/download.py windows/main_window.py windows/progress.py windows/settings.py windows/view.py --noconsole --clean --onefile
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: main.exe
        path: dist/
  release_assets:
    name: Release assets
    needs:
      - build-ubuntu
      - build-windows
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - os: ubuntu-latest
          - os: windows-latest
        names:
          - name: main
          - name: main.exe
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.names.name }}
